# BarberPe - gestion de barberias. https://barberpe.froggydevs.com
APP_NAME="BarberPe"
APP_REPO="https://github.com/jimyhdolores/app-barber.git"
APP_DIR="app-barber"
APP_BRANCH="main"
APP_TIERS="backend frontend"
APP_ENABLED="1"
APP_DB="app_barber_db"
APP_DB_BOOTSTRAP_SQL=""

TIER_backend_COMPOSE="infra/backend/docker-compose.yml"
TIER_backend_CONTAINER="barber-api"
TIER_backend_ENV_FILE="apps/backend-nestjs/.env"
TIER_backend_WAIT="90"

TIER_frontend_COMPOSE="infra/frontend/docker-compose.yml"
TIER_frontend_CONTAINER="barber-web"
TIER_frontend_ENV_FILE=""
TIER_frontend_WAIT="45"
